### ISSUE TITLE
Customize what can and can't be kept

### ISSUE THREAD

**Issue by Darkhand81** [robinjam/keep-items#2]
Hi!

I'd love to have the ability to customize what can and can't be kept.

Two modes, inclusive and exclusive.

One mode would set only certain item numbers to drop... That way a player could keep their inventory but still give other players a small reward for killing them... For example they might lose all the ore they've been mining but keep everything else.

Then the inverse of that, another mode to set certain item numbers to be kept... That way they would lose everything but hang on to their armor and weapons, for example.

Thanks in advance!

**Comment by robinjam** [comment]
This is a good idea. Perhaps I could implement it with permissions - in order to keep an item when you die, you would need the keep-items.item.<id> permission. That way you could allow different groups of people to keep different sets of items, or even customise it per-world if your permissions plugin supports that. Sound like a plan?

**Comment by Darkhand81** [comment]
Sounds perfect!! I'd put this plugin into production in an instant with that functionality.. :)

**Comment by robinjam** [comment]
This is implemented now and will be in the next release. Thanks for the suggestion!

**Comment by Darkhand81** [comment]
Fantastic!  Thanks so much for your efforts!
